#
# Questo e' un progetto d'esempio in formato OpenAPI 3.0 API Starter Kit.
#
# Stai per sviluppare un API? Segui attentamente questo template e
#   potrai integrarla facilmente in Developers Italia.
#
x-commons:
  ratelimit-headers: &ratelimit-headers
    X-RateLimit-Limit:
      $ref: '#/components/headers/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: '#/components/headers/X-RateLimit-Remaining'
    X-RateLimit-Reset:
      $ref: '#/components/headers/X-RateLimit-Reset'
  common-responses: &common-responses
    '403':
      $ref: >-
        #/components/responses/403Forbidden
    '400':
      $ref: '#/components/responses/400BadRequest'
    '429':
      $ref: '#/components/responses/429TooManyRequests'
    '503':
      $ref: '#/components/responses/503ServiceUnavailable'
    default:
      $ref: '#/components/responses/default'

openapi: 3.0.0
info:
  version: "1.0.0"
  title: |-
    Patente AA.
  x-summary: >-
    Fornisce l'attributo patente di guida.
  description: |
    Documentazione
    ...
  x-spid:
    # Questa sezione è obbligatoria §2.1
    aa-version: 1.0.0
    aa-home: https://aa.example/patente/v1/u1/openapi.yaml
    aa-registry: https://spid.gov.it/aa/registry/patente/v1/openapi.yaml
    
  termsOfService: 'http://swagger.io/terms/'
  # Chi posso contattare per informazioni sul servizio e sul suo stato?
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: https://twitter.com/ioggstream
  # L'audience delle API. Attualmente e' definito solamente
  #   la tipologia `public`.
  x-audience:
    - public
  # Ogni API deve avere un UUID, invariante nel tempo e
  #   rispetto al `title`.
  x-api-id: 00000000-0000-0000-0000-000000000000
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
# Una lista di `tag` utili a raggruppare le varie operazioni
#   eseguite dalle API. Ogni `tag` puo' referenziare un link
#   alla sua descrizione.
tags:
  - name: public
    description: Retrieve informations v. §2.7
    externalDocs: &lg-spid-aa
      description: Linee Guida Spid AA
      url: https://agid.gov.it/riferimento-lg-spid-aa
  - name: protected
    description: Accesso permesso per enti e SP convenzionati, v. §2.7
    externalDocs:
      <<: *lg-spid-aa
  - name: private
    description: Accesso previo consenso v. §2.7
    externalDocs:
      <<: *lg-spid-aa

servers:
  - description: |-
      I server devono rispettare una serie di indicazioni
    url: https://aa.example/patente/{version}
    
  - description: Development server
    url: https://localhost:8443/patente/{version}


#
# Qui vanno tutti i path.
#
paths:
  /patente/{tax_code}:
    get:
      parameters:
      - name: tax_code
        in: path
        required: true
        schema:
          type: string
          description: |-
            il codice fiscale del soggetto
      summary: Ritorna un timestamp in formato RFC5424.
      description: |
        Ritorna un timestamp in formato RFC5424
        prendendola dal server attuale.
      operationId: get_echo
      security:
      - MODI: []
      - ConsensoUtente: [openid, profile, offline_access, "patente:full", "patente:minimal", "patente:boolean"]
      tags:
        - private
      responses:
        <<: *common-responses
        '200':
          description: |
            Il server ha ritornato il timestamp.
          # Questi header di throttling sono obbligatori e definiti
          #   nel Nuovo modello di interoperabilità.
          headers:
            <<: *ratelimit-headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patente'

  /status:
    get:
      summary: Ritorna lo stato dell'applicazione.
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: get_status
      tags:
        - public
      responses:
        <<: *common-responses
        '200':
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          # Questi header di throttling sono obbligatori e definiti
          #   nel Nuovo modello di interoperabilità.
          headers:
            <<: *ratelimit-headers
            Cache-Control:
              $ref: '#/components/headers/Cache-Control'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  securitySchemes:
    MODI:
      type: http
      scheme: bearer
      bearerFormat: jwt
      description: |-
        Questo modello prevede il passaggio di un JWT
        contenente le seguenti informazioni
        conformi alle indicazioni del MODI
        eg. basato su [ID_AUTH_REST_01](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/02_Pattern%20sicurezza/05_accesso-del-fruitore/03_id_auth_rest_01.html)
      
    ConsensoUtente:
      description: |-
        Questa sezione esplicita il riferimento all'URL di configurazione
        di OIDC relativo al provider. Deve contenere le informazioni
        indicate in:
        [oidc discovery](https://openid.net/specs/openid-connect-discovery-1_0.html)
        e simile a quanto visto in [spid oidc](https://docs.italia.it/AgID/documenti-in-consultazione/lg-openidconnect-spid-docs/it/bozza/metadata/openid-provider-op-metadata.html?highlight=metadata)
        ad esempio:
        ```
        {
          "issuer": "https://aa.spid.it/",
          "authorization_endpoint": "https://aa.spid.it/authorize",
          "token_endpoint": "https://aa.spid.it/token",
          "jwks_uri": "https://aa.spid.it/.well-known/jwks.json",
          "scopes_supported": [
            "openid",
            "profile",
            "offline_access",
            "patente:full",
            "patente:minimal",
            "patente:boolean"
          ],
          "response_types_supported": [
            "code",
          ],
          "token_endpoint_auth_methods_supported": [
            "private_key_jwt"
          ],
          "subject_types_supported":[
            "public"
          ],
          ...
        }

        ```
      type: openIdConnect
      openIdConnectUrl: https://aa.spid.it/.well-known/openid-configuration

  examples:
    403Forbidden:
      summary: §2.3 Consenso non fornito
      value: 
        title: Forbidden
        status: 403
        detail: Consent Required
        instance: https://aa.spid.it/.well-known/openid-configuration
  headers:
    Cache-Control:
      schema:
        type: string
    X-RateLimit-Limit:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/headers/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/headers/X-RateLimit-Remaining'
    X-RateLimit-Reset:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/headers/X-RateLimit-Reset'
    Retry-After:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/headers/Retry-After'

  responses:
    # Predefined error codes for this API
    403Forbidden:
      description: |-
        Questa risposta viene data ad un SP quando gli attributi
        sono accessibili solo previo consenso
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples: 
            403Forbidden:
              $ref: '#/components/examples/403Forbidden'
      $ref: >-
        https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/403Forbidden

    400BadRequest:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/400BadRequest'
    404NotFound:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/404NotFound'
    429TooManyRequests:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/429TooManyRequests'
    503ServiceUnavailable:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/503ServiceUnavailable'
    default:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/responses/default'

  schemas:
    XSpid:
      type: object
      required:
        - aa-version
        - aa-home
        - aa-registry
      properties:
        aa-version:
          type: string
          example: 1.0.0
        aa-home:
          type: string
          format: url
        aa-registry:
          type: string
          format: url
    Problem:
      $ref: 'https://teamdigitale.github.io/openapi/0.0.5/definitions.yaml#/schemas/Problem'
    Patente:
      type: object
      description: Patente di guida
      externalDocs:
        url: http://www.mit.gov.it/documentazione/patenti-di-guida-informazioni-riconoscimento-sostituzione-relative-alla-patente-di
      properties:
        patente:
          type: string
          description: |-
            Il pattern di validazione delle patenti è qui http://www.mit.gov.it/normativa/Circolare_protocollo_30039_24-10-2011
          pattern: "UI[A-Z0-9]+"
        emessa_il:
          type: string
          format: date-time
          example: '2018-12-30T12:23:32Z'
